# Métodos computacionales para el aprendizaje automático

## Objetivos



*   Aprender conceptos básicos del aprendizaje automático.
*   Conocer y manejar las herramientas computacionales que se utilizan en el campo del aprendizaje automático.

## Organización de las clases



1.   Introducción a R en google colab
2.   Introducción a Git y GitHub
3.   Modelos lineales regularizados con R.
4.   Metodos no superivsados con R (clustering)
5.   Introducción a las redes neuronales combinando R y Python

# Introducción de R en google colab

## Habilitar R

Cuándo se abre google colab el lenbguaje base es siempre python, pero existe una forma de trabajar con R también. 

1- Primero hay que abrir el navegador

2- Colocar alguna de las siguientes URL:
  
   - https://colab.research.google.com/#create=true&language=
   - https://colab.to/r

Para poder ingresar tienen que tener abierta su sesion de Google drive

Google Colaboratory proporciona la posibilidad de trabajar en la nube lo que permite usar el potencial de máquina que ofrece google. No es el único que trabaja de esta manera, existen otras plataformas que trabajan igual:

- Binder: https://mybinder.org/ es gratuito pero hay que tener el código en github. Trabaja R, Python y Julia
- Kaggle: https://www.kaggle.com/ ideal para practicar además tiene bases de datos disponibles. Trabaja R y Python
- Microsoft Azure: ofrece horas gratis pero es de pago
- JetBrains datalore : También tiene horas gratis el resto es pago

## Estructuras de datos

### Vectores en R

Los vectores siempre contienen elementos de un mismo tipo. Se construyen con la función c. Si se agrega un dato de tipo distino a los que tiene el vector este transforma todos los datos en en tipo más genérico que pueda soportar a todos los elementos que contiene.

In [ ]:
x <- c(5,6,8)
x

[1] 5 6 8

In [ ]:
x[2]

[1] 6

Para elegir un elemento se pone su posición entre corchetes. Esté además puede ser modificado por lo que es un objeto de tipo mutable

In [ ]:
x[2] <- 7
x

[1] 5 7 8

### Matrices y arrays

Las matrices se podrían considerar como vectores de  dos dimensiones, por lo tanto al igual que un vector pueden tener datos de un solo tipo. Un array es una generalización de las matrices y puede adoptar cualquier dimensión, aunque también es encesario qeu sean del mismo tipo los elementos. En machine learning se usan mucho los tensores que son arrays de matrices.

Para crear una matriz se utiliza el comando *matrix()*. Esta función acepta un argumento que son los datos y luego dos argumentos más que son el número de filas *nrows* y el número de columnas *ncol*.

In [ ]:
A <- matrix(1:12, 3,4 )
A

     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10
[2,] 2    5    8    11
[3,] 3    6    9    12

Para elegir un elemento de le matriz, se debe indicar el número de fila y el número de columna en el cual está el elemento

In [ ]:
A[2,3]

[1] 8

También se puede elegir un elemento marcando la posición que tiene el elemento contando como si fuera un vector

In [ ]:
A[5]

[1] 5

En caso que se quiera seleccionar una fila o una columna entera no se pone nada en esa posición y se acompaña la coma. $M[f,]$ para elegir una fila, $M[,c]$ para elegir una columna

In [ ]:
A[2,]

[1]  2  5  8 11

In [ ]:
A[,3]

[1] 7 8 9

Otra forma de crear matrices es con las funciones *cbind* y *rbind* para apilar vectores en columnas y vectores en filas respectivamente

In [ ]:
cbind(c(1:4), c(2:5))

     [,1] [,2]
[1,] 1    2
[2,] 2    3
[3,] 3    4
[4,] 4    5

In [ ]:
rbind(c(1:4), c(2:5))

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4
[2,] 2    3    4    5

### Data frames

Los data frames son matrices que pueden adoptar cualquier tipo de dato. Son muy utilizados para trabajar, porque es el formato que adopatan las bases de datos. Las columnas de un dataframe son vectores, por lo tanto solo aceptan datos de un solo tipo, en el caso de las filas si se aceptan diferentes tipo de datos.

Para crear un data frame se usa la función *data.frame()* y se le pueden agregar nombres a las columnas

In [ ]:
mi_df <- data.frame(
  "entero" = 1:4, 
  "factor" = as.factor(c("a", "b", "c", "d")), 
  "numero" = c(1.2, 3.4, 4.5, 5.6),
  "cadena" = as.character(c("a", "b", "c", "d"))
)

mi_df

  entero factor numero cadena
1 1      a      1.2    a
2 2      b      3.4    b
3 3      c      4.5    c
4 4      d      5.6    d

In [ ]:
# la función dim arroja la cantidad de filas y columnas que tiene el df

dim(mi_df)

[1] 4 4

In [ ]:
# la función length arrija la cantidad de columnas
length(mi_df)

[1] 4

Para seleccionar elementos se trabaja de la misma forma que para una matriz, con un adicional, acá se puede elegir una columna de acuerdo al nombre que le hayamos puesto

In [ ]:
mi_df['factor']

  factor
1 a
2 b
3 c
4 d

In [ ]:
# fila 3 de la columna factor
mi_df[3,'factor']

[1] c
Levels: a b c d

### Listas

Las listas son unidimensionales como los vectores, pero pueden contener cualquier elemento dentro de ellas, incluso otras listas. Se pueden crear con la función *list()*

In [ ]:
lista1 <- list(c(5,4), matrix(1:4,2,2), 4,'pepe')
lista1

[[1]]
[1] 5 4

[[2]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[3]]
[1] 4

[[4]]
[1] "pepe"

In [ ]:
lista2 <- list(lista1, mi_df)
lista2

[[1]]
[[1]][[1]]
[1] 5 4

[[1]][[2]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[1]][[3]]
[1] 4

[[1]][[4]]
[1] "pepe"


[[2]]
  entero factor numero cadena
1      1      a    1.2      a
2      2      b    3.4      b
3      3      c    4.5      c
4      4      d    5.6      d

In [ ]:
lista2[[1]][3]

[[1]]
[1] 4

## Condicionales if y else

La función if sirve para ejecutar una dfeterminada función siempre que ocurra alguna condición en particular. La estructura de la misma en R se escribe de la siguiente forma:

    if (condición) {

      operaciones

    }
 
Esto nos dice que va hacer el programa cuando ocurra la condición, en caso de que esto no suceda no va pasar nada. Si queremos agregar operaciones que actuén en caso de falsedad de la condicíon hay que agregar el comando *else*

    if (condición) {
    
      opearciones si se cumple
    
    } else 
    {
    
      operaciones si no se cumple
    
    }
  

**Ejemplo**

Excluir la división por 0

In [ ]:
n = 6
d = 2

if (d != 0){
    print (n/d)
    } else 
    {
    print('no se puede dividir por 0')
          }

[1] 3

### ifelse

El comando ifelse opera cuando queremos trabajar sobre listas, nos va devolever el grado de verdad por cada elemento de la lista.

Estructura:

    ifelse( vector y condición, valor si es verdadero, valor si es falso)

In [ ]:
n = 6
d = c(0,2,3)

ifelse(d == 0, 'No se puede dividir', 6/d)

[1] "No se puede dividir" "3"                   "2"

## Iterar en R

Una de las funciones principales para crear un programa es manejar las iteraciones o bucles

### Instrucción for

    for (i in secuencia) {
  
      operación 1
  
      ...
  
      operación final
  
    }

**Ejemplo** 

Multiplicación de dos vectores

In [ ]:
a <- c(2,6,4)
b <- c(5,7,2)

rdo <- numeric()  #creamos un vector vacío

for (i in 1:length(a)){
  x <- a[i]*b[i]
  rdo[i] <- x
}

rdo

[1] 10 42  8

In [ ]:
a*b

[1] 10 42  8

### Instrucción while

    while (condición) {

     operación 1

      ...

    operación final 
  
    }

**Ejemplo**

Serie de Fibonacci

In [ ]:
max <- 10 
i <- 0  #iterador
rdo <- numeric()

while (i < max) {
  if (length(rdo) < 2) {
     rdo[i] <- 1
      }
  else{
    rdo[i] <- rdo[i-1]+rdo[i-2]
  }
  i <- i+1  #importante para no tener un bucle infinito
}

rdo

[1]  1  1  2  3  5  8 13 21 34

## Funciones

Estructura

    nombre_de_función <- function(variable1, variable2,...){
  
    cuerpo

    return(resultado)
    }


Por ejemplo función que devuelve la serie de Fibonacci

In [ ]:
Fibonacci <- function(cantidad_digitos){
  i <- 0  #iterador
  rdo <- numeric()

while (i <= cantidad_digitos) {
  if (length(rdo) < 2) {
     rdo[i] <- 1
      }
  else{
    rdo[i] <- rdo[i-1]+rdo[i-2]
  }
  i <- i+1  #importante para no tener un bucle infinito
}

return(rdo)

}

In [ ]:
Fibonacci(8)
Fibonacci(6)

[1]  1  1  2  3  5  8 13 21

[1] 1 1 2 3 5 8

## Carga de base de datos

Existe la función básica para leer archivos que viene con R, que es "read.csv". Pero también la librería tidyverse tiene la función read_csv o read_excel que por lo general se recomienda, ya que carga más rápido y transfomra los datos

In [ ]:
library(tidyverse)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.6     ✔ purrr   0.3.4
✔ tibble  3.1.7     ✔ dplyr   1.0.9
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [ ]:
datos <- read_csv("WineQT.csv")
head(datos)

Rows: 1143 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (13): fixed acidity, volatile acidity, citric acid, residual sugar, chlo...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  fixed acidity volatile acidity citric acid residual sugar chlorides
1  7.4          0.70             0.00        1.9            0.076
2  7.8          0.88             0.00        2.6            0.098
3  7.8          0.76             0.04        2.3            0.092
4 11.2          0.28             0.56        1.9            0.075
5  7.4          0.70             0.00        1.9            0.076
6  7.4          0.66             0.00        1.8            0.075
  free sulfur dioxide total sulfur dioxide density pH   sulphates alcohol
1 11                  34                   0.9978  3.51 0.56      9.4
2 25                  67                   0.9968  3.20 0.68      9.8
3 15                  54                   0.9970  3.26 0.65      9.8
4 17                  60                   0.9980  3.16 0.58      9.8
5 11                  34                   0.9978  3.51 0.56      9.4
6 13                  40                   0.9978  3.51 0.56      9.4
  quality Id
1 5       0
2 5       1
3 5       2
4 6       3
5 5       4
6 5       5

Con la función filter podemos obtener un subconjunto de los datos, podemos pasarle condiciones de:

- igualdad: ==
- desigual: != 
- mayor o menor: ><
- combinar con operadores lógicos:
  
    & significa and

    | significa or

In [ ]:
head(filter(datos, quality == 8 & alcohol > 10))

  fixed acidity volatile acidity citric acid residual sugar chlorides
1  7.9          0.35             0.46        3.6            0.078
2 10.3          0.32             0.45        6.4            0.073
3  5.6          0.85             0.05        1.4            0.045
4 11.3          0.62             0.67        5.2            0.086
5  9.4          0.30             0.56        2.8            0.080
6 10.7          0.35             0.53        2.6            0.070
  free sulfur dioxide total sulfur dioxide density pH   sulphates alcohol
1 15                  37                   0.9973  3.35 0.86      12.8
2  5                  13                   0.9976  3.23 0.82      12.6
3 12                  88                   0.9924  3.56 0.82      12.9
4  6                  19                   0.9988  3.22 0.69      13.4
5  6                  17                   0.9964  3.15 0.92      11.7
6  5                  16                   0.9972  3.15 0.65      11.0
  quality Id
1 8       267
2 8       278
3 8       390
4 8       455
5 8       481
6 8       495

Si queremos seleccionar columnas, con la función select se puede hacer muy fácilmente, poniendo la base de datos y al lado separado por coma, cada uno de los campos a utilizar

In [ ]:
head(select(datos, pH,alcohol,quality))

  pH   alcohol quality
1 3.51 9.4     5
2 3.20 9.8     5
3 3.26 9.8     5
4 3.16 9.8     6
5 3.51 9.4     5
6 3.51 9.4     5

Con el operador pipe %>% se puede ir pasando las diferentes funciones que queremos realizar a la base de datos. De esta forma queda el código más prolijo

In [ ]:
datos %>%
  filter(quality == 8 & alcohol > 10)%>%
  select(pH,alcohol,quality)

   pH   alcohol quality
1  3.35 12.8    8
2  3.23 12.6    8
3  3.56 12.9    8
4  3.22 13.4    8
5  3.15 11.7    8
6  3.15 11.0    8
7  3.15 11.0    8
8  3.72 14.0    8
9  3.21 12.5    8
10 2.98 11.8    8
11 3.20 13.1    8
12 3.35 11.7    8
13 3.23 11.3    8
14 3.24 11.4    8

## Familia de funciones apply

La función apply() se aplica a un dataframe, matriz, lista o vector. El segundo argumento es para definir si se aplica a las filas 1, o a las columnas 2

In [ ]:
n_data <- select(datos, pH,alcohol,quality)

r <- apply(n_data, 2, mean)
r

       pH   alcohol   quality
 3.311015 10.442111  5.657043

La función lapply() y sapply() son similares, solo que devuelve una lista y un vector respectivamente y siempre actúan sobre columnas

In [ ]:
r <- lapply(n_data,mean)
r

$pH
[1] 3.311015

$alcohol
[1] 10.44211

$quality
[1] 5.657043

In [ ]:
r <- sapply(n_data,mean)
r

       pH   alcohol   quality
 3.311015 10.442111  5.657043

La función tapply sirve para aplicar una función pero de manera agrupada.

In [ ]:
tapply(n_data$alcohol,n_data$quality, mean)

        3         4         5         6         7         8
 9.691667 10.260606  9.902277 10.655339 11.482634 11.937500